In [6]:
from data_extraction import DataExtractor
from database_utils import DatabaseConnector
import pandas as pd
DE = DataExtractor()
DC = DatabaseConnector()
user_data = DE.read_rds_table(DC, "legacy_users")
display(user_data.head(100))

,index,first_name,last_name,date_of_birth,company,email_address,address,country,country_code,phone_number,join_date,user_uuid
0,0,Sigfried,Noack,1990-09-30,Heydrich Junitz KG,rudi79@winkler.de,Zimmerstr. 1/0\n59015 Gießen,Germany,DE,+49(0) 047905356,2018-10-10,93caf182-e4e9-4c6e-bebb-60a1a9dcf9b8
1,1,Guy,Allen,1940-12-01,Fox Ltd,rhodesclifford@henderson.com,Studio 22a\nLynne terrace\nMcCarthymouth\nTF0 9GH,United Kingdom,GB,(0161) 496 0674,2001-12-20,8fe96c3a-d62d-4eb5-b313-cf12d9126a49
2,2,Harry,Lawrence,1995-08-02,"Johnson, Jones and Harris",glen98@bryant-marshall.co.uk,92 Ann drive\nJoanborough\nSK0 6LR,United Kingdom,GB,+44(0)121 4960340,2016-12-16,fc461df4-b919-48b2-909e-55c95a03fe6b
3,3,Darren,Hussain,1972-09-23,Wheeler LLC,daniellebryan@thompson.org,19 Robinson meadow\nNew Tracy\nW22 2QG,United Kingdom,GB,(0306) 999 0871,2004-02-23,6104719f-ef14-4b09-bf04-fb0c4620acb0
4,4,Garry,Stone,1952-12-20,Warner Inc,billy14@long-warren.com,3 White pass\nHunterborough\nNN96 4UE,United Kingdom,GB,0121 496 0225,2006-09-01,9523a6d3-b2dd-4670-a51a-36aebc89f579
...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,Oliver,Jacob,1949-11-11,Eimer,concettadrub@fritsch.net,Johannes-Drubin-Ring 9\n41950 Jessen,Germany,DE,(01756) 82716,2019-08-11,0bd028f1-02c0-4441-8535-299a2e8db939
96,96,Vitali,Löwer,1955-12-29,Knappe Linke Stiftung & Co. KGaA,gbeyer@trueb.de,Trubinweg 62\n43281 München,Germany,DE,(00632) 193546,2019-12-11,fd0d7355-892c-4192-b9ef-282ef3d8e6f6
97,97,Samantha,Patel,1976-03-11,Smith-Vincent,nashrobert@thompson.net,1 Ward estate\nLake Rogerside\nDH3 5HE,United Kingdom,GB,+44(0)1614960324,2015-12-25,aa9560a5-8f64-47e7-8fd7-a32846c790ca
98,98,Jasmine,Davies,1991-10-05,Shepherd-Patel,wilsoncharlene@singh.co.uk,Studio 9\nDanny square\nLindseybury\nCV27 8RP,United Kingdom,GB,+44(0)1174960171,1993-11-28,adb4bfee-9625-40f8-aaa7-53e54b58f274
99,99,Dean,Booth,1981-10-23,"Chapman, Russell and Thompson",griffithsdebra@clarke-pearce.net,177 Wood points\nWest Albert\nBN09 3AB,United Kingdom,GB,+44(0)1632960663,2014-01-26,87e945d4-bc8d-423c-b786-0cede8d0b159

In [8]:
print(user_data.loc[752])

index                   752
first_name       PYCLKLLC7I
last_name        W350SCUD6R
date_of_birth    KBTI7FI7Y3
company          R7IZUNSQX0
email_address    3Q791B3VIY
address          YW2YXLOQ5J
country          I7G4DMDZOZ
country_code     VSM4IZ4EL3
phone_number     A4Q4HQBI3I
join_date        JJ2PDVNPRO
user_uuid        W43MSCMQ88
Name: 752, dtype: object